name: 🚀 Build, Test, and Upload on Develop Push

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🧑‍💻 Checkout Repository
      uses: actions/checkout@v4

    - name: 🔧 Set Up .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: 📦 Restore Dependencies
      run: dotnet restore

    - name: Install Playwright Browsers
      run: |
        npm install -g playwright
        npx playwright install

    - name: Install Playwright Browsers for .NET
      run: pwsh -c "pwsh bin/Debug/net9.0/playwright.ps1 install"

    - name: 🏗️ Build Project
      run: dotnet build --configuration Release

    - name: Set up XVFB
      run: |
        sudo apt-get install -y xvfb
        nohup Xvfb :99 -ac -screen 0 1280x1024x24 &

    - name: 🧪 Run Tests
      run: dotnet test --configuration Release

    - name: 📦 Publish Project
      if: success()
      run: dotnet publish --configuration Release --output ./publish

    - name: 📤 Upload Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

  download-artifact:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: ⬇️ Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./downloaded-publish